services:

  # Psr log message processor
  service_bus.logger.processors.psr_message:
    class: Monolog\Processor\PsrLogMessageProcessor

  # Memory usage logger processor
  service_bus.logger.processors.memory_usage:
    class: Monolog\Processor\MemoryUsageProcessor
    arguments:
      $realUsage: true

  # Process id logger processor
  service_bus.logger.processors.process_id:
    class: Monolog\Processor\ProcessIdProcessor

  # Echo stream handler
  service_bus.logger.handlers.stdout_handler:
    class: Desperado\ServiceBus\Infrastructure\Logger\Handlers\StdOut\StdOutHandler

  # Graylog handler
  #service_bus.logger.handlers.graylog_handler:
    #class: Desperado\ServiceBus\Infrastructure\Logger\Handlers\Graylog\GelfUdpHandler
    #arguments:
      #$host: '%app.logger.graylog.udp_host%'
      #$port: '%app.logger.graylog.udp_port%'
      #$gzipMessage: false

  # Default logger instance
  service_bus.logger:
    class: Monolog\Logger
    arguments:
      $name: '%service_bus.entry_point%'
      $handlers:
        - '@service_bus.logger.handlers.stdout_handler'
        #- '@service_bus.logger.handlers.graylog_handler'
      $processors:
        - '@service_bus.logger.processors.memory_usage'
        - '@service_bus.logger.processors.process_id'
        - '@service_bus.logger.processors.psr_message'